server {
	listen 80;
	server_name localhost;

	access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log info;

	root /var/www/html/final/public;
	index index.php index.html;

	# --- Zaverecne Zadanie ---

	location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

	# Vite dev server proxy
	location /@vite {
		proxy_pass http://php:5173;
	}

	location /resources/ {
        proxy_pass http://php:5173;
    }

    location /node_modules/ {
        proxy_pass http://php:5173;
	}
	
	# ---------------

	# Do not pass .css or other files to PHP
	location ~* \.(css|js|jpg|jpeg|png|gif|ico)$ {
		try_files $uri =404;
		expires 7d;
		access_log off;
	} 

	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	location ~ /\.ht {
		deny all;
	}
}
